Countdown:
  Lobby: 120
  Full: 30
  Warmup: 20
  Ingame: 120
  End: 20
Players:
  spectator: 20
  max: 10
  min: 1
  seeker: 1
  skip-lobby: 8
MySQL:
  host: 127.0.0.1:3306
  database: hidenseek
  user: hidenseek
  password: password
motd:
  Lobby: "&aLobby"
  Full: "&eFull"
  Warmup: "&cWarmup"
  Ingame: "&cIngame"
  End: "&4End"
points:
  found: 10
  cought: 5
  win: 10
  play: 5
  hint:
    firework: 10
    meow: 5
    explosion: 5
props:
  wait: 5
language:
  default-file: en.yml
colors:
  primary: "&7"
  secondary: "&e"
  warning: "&c"
prefix:
  chat: "&eHide'n'Seek &8&l> %cp%"
  item: "&7> &a"
  inv-item: "&7>> &b"
  inv-names: "&b> &7"
items:
  stun-duration: 10
  firework-duration: 30
  meow-duration: 5
  explosion-duration: 15
spawnpoint-lobby:
  X: -99.5
  Y: 69.0
  Z: 100.5
  Yaw: -83.5
  Pitch: 54.5
  World: world
Tablist:
  enabled: true
  Lobby:
    Header:
      - "&bHide'n'Seek"
    Footer:
      - "Visit: &bgithub.com/Niklashere/Spigot_Hidenseek"
  WarmUp:
    Header:
      - "&bHide'n'Seek"
    Footer:
      - "Visit: &bgithub.com/Niklashere/Spigot_Hidenseek"
  Ingame:
    Header:
      - "&bHide'n'Seek"
    Footer:
      - "Visit: &bgithub.com/Niklashere/Spigot_Hidenseek"
  End:
    Header:
      - "&bHide'n'Seek"
    Footer:
      - "Visit: &bgithub.com/Niklashere/Spigot_Hidenseek"
Ranks:
  - Admin
  - Moderator
  - Supporter
  - Player
Displaynames:
  enabled: true
  Seeker: "&c"
  Hider: "&a"
  Spectator: "&7&o"
  Lobby:
    Admin: 
      Prefix: "&4&lAdmin&f "
      Suffix: ""
    Moderator: 
      Prefix: "&2&lModerator&f "
      Suffix: ""
    Supporter: 
      Prefix: "&a&lSupporter&f "
      Suffix: ""
    Player: 
      Prefix: ""
      Suffix: ""
  WarmUp:
    Admin: 
      Prefix: "%role% "
      Suffix: ""
    Moderator: 
      Prefix: "%role% "
      Suffix: ""
    Supporter: 
      Prefix: "%role% "
      Suffix: ""
    Player: 
      Prefix: "%role% "
      Suffix: ""
  Ingame:
    Admin: 
      Prefix: "%role% "
      Suffix: ""
    Moderator: 
      Prefix: "%role% "
      Suffix: ""
    Supporter: 
      Prefix: "%role% "
      Suffix: ""
    Player: 
      Prefix: "%role% "
      Suffix: ""
  End:
    Admin: 
      Prefix: "&4&lAdmin&f "
      Suffix: ""
    Moderator: 
      Prefix: "&2&lModerator&f "
      Suffix: ""
    Supporter: 
      Prefix: "&a&lSupporter&f "
      Suffix: ""
    Player: 
      Prefix: ""
      Suffix: ""
PlayerListName:
  enabled: true
  Seeker: "&c"
  Hider: "&a"
  Spectator: "&7&o"
  Lobby:
    Admin: "&4&lAdmin&f %pp%"
    Moderator: "&2&lModerator&f %pp%"
    Supporter: "&a&lSupporter&f %pp%"
    Player: "%pp%"
  WarmUp:
    Admin: "%role%%pp%"
    Moderator: "%role%%pp%"
    Supporter: "%role%%pp%"
    Player: "%role%%pp%"
  Ingame:
    Admin: "%role%%pp%"
    Moderator: "%role%%pp%"
    Supporter: "%role%%pp%"
    Player: "%role%%pp%"
  End:
    Admin: "&4&lAdmin&f %pp%"
    Moderator: "&2&lModerator&f %pp%"
    Supporter: "&a&lSupporter&f %pp%"
    Player: "%pp%"
Chat:
  enabled: true
  Seeker: "&c"
  Hider: "&a"
  Spectator: "&7&o"
  Lobby:
    Admin: "&4&lAdmin&f %pp%&8: &7"
    Moderator: "&2&lModerator&f %pp%&8: &7"
    Supporter: "&a&lSupporter&f %pp%&8: &7"
    Player: "%pp%&8: &7"
  WarmUp:
    Admin: "%role%%pp%&8: &7"
    Moderator: "%role%%pp%&8: &7"
    Supporter: "%role%%pp%&8: &7"
    Player: "%role%%pp%&8: &7"
  Ingame:
    Admin: "%role%%pp%&8: &7"
    Moderator: "%role%%pp%&8: &7"
    Supporter: "%role%%pp%&8: &7"
    Player: "%role%%pp%&8: &7"
  End:
    Admin: "&4&lAdmin&f %pp%"
    Moderator: "&2&lModerator&f %pp%&8: &7"
    Supporter: "&a&lSupporter&f %pp%&8: &7"
    Player: "%pp%&8: &7"
