Lobby: 20
Full: 20
Warmup: 20
Ingame: 120
End: 20
max-players: 10
min-players: 1
max-seeker: 1
skip-lobby-countdown: 8
skip-lobby-time: 30
spawnpoint-lobby:
  X: -99.33487143047729
  Y: 69.0
  Z: 100.53326965213392
  Yaw: -83.85
  Pitch: 54.34994
  World: world
MySQL:
  host: 192.168.0.1:3306
  database: hidenseek
  user: hidenseek
  password: password
points:
  found: 10
  cought: 5
  win: 10
  play: 5
stun-duration: 10